apiVersion: v1
kind: ReplicationController
metadata:
  name: activemq-rc
  namespace: liyang
  labels:
    name: activemq-rc
spec:
  replicas: 1
  selector:
    name: activemq-pod
  template:
    metadata:
      labels:
        name: activemq-pod
    spec:
      containers:
        - name: activemq
          image: rmohr/activemq:5.10.0
          imagePullPolicy: Never
          ports:
            - name: http8161
              containerPort: 8161
            - name: http61616
              containerPort: 61616

---
apiVersion: v1
kind: Service
metadata:
  name: activemq-svc
  namespace: liyang
  labels:
    name: activemq-svc
spec:
  type: NodePort
  ports:
    - port: 8161
      protocol: TCP
      targetPort: 8161
      name: http8161
      nodePort: 23456
    - port: 61616
      protocol: TCP
      targetPort: 61616
      name: http61616
      nodePort: 23457
  selector:
    name: activemq-pod