apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-rc
  namespace: liyang
  labels:
    name: redis-rc
spec:
  replicas: 1
  selector:
    name: redis-pod
  template:
    metadata:
      labels:
        name: redis-pod
    spec:
      containers:
        - name: redis
          image: redis:5.7
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: liyang
  labels:
    name: redis-svc
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: http
      nodePort: 33306
  selector:
    name: redis-pod