apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-rc
  namespace: liyang
  labels:
    name: redis-rc
spec:
  replicas: 1
  selector:
    name: redis-pod
  template:
    metadata:
      labels:
        name: redis-pod
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: liyang
  labels:
    name: redis-svc
spec:
  type: NodePort
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      name: http
      nodePort: 20002
  selector:
    name: redis-pod