apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-boot
  namespace: liyang
  labels:
    name: spring-boot-rc
spec:
  replicas: 1
  selector:
    name: spring-boot-pod
  template:
    metadata:
      labels:
        name: spring-boot-pod
    spec:
      containers:
        - name: springboot-demo
          image: springboot-demo:20190928.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-svc
  namespace: liyang
  labels:
    name: spring-boot-svc
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      name: http
      nodePort: 20001
  selector:
    name: spring-boot-pod
