server:
  port: 8082 #Tomcat端口
spring:
  dubbo:
    application:
      name: sb-dubbo-customer #应用名
    registry:
      address: zookeeper://192.168.17.21 #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20890 #dubbo服务暴露的端口
    scan: com.liyang.sb.controller #扫描的包名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.17.21:3306/mydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Passw0rd

logging:
  level:
    org:
      springframework=DEBUG:
