server:
  port: 8081 #Tomcat???
spring:
  dubbo:
    application:
      name: sb-dubbo-provider #?????
    registry:
      address: zookeeper://192.168.17.21 #zookeeper???
      port: 2181 #????????
    protocol:
      name: dubbo
      port: 20890 #dubbo?????????
    scan: com.liyang.sb.service.impl #???????
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.17.21:3306/mydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Passw0rd
  redis:
    database: 0 # 数据库索引默认为0
    host: 192.168.17.21
    port: 6739
    password: 123456
    pool:
      max-active: 200 # 连接池最大连接数
      max-wait: -1 # 连接池最大阻塞时间
    timeout: 1000

# springboot -- mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  config-location: classpath:mapper.config.sqlMapConfig.xml
  type-aliases-package: com.liyang.sb.bean

# 日志配置
logging:
  level:
    org:
      springframework=DEBUG:
